config/routes.rb
Rails.application.routes.draw do
  get 'events/upcoming'

  get 'events/past'

  get 'maps/google_maps'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts
  resources :messages, only: [:new, :create]
  resources :messages
  devise_for :users
  get 'home/about'
  get 'fusion', to: 'home#fusion'
  get 'chat', to: 'home#chat'
  get 'blog', to: 'home#blog'
  get 'frapp_talk', to: 'home#blog'
  get 'maps', to: 'home/maps#maps'
  get 'content', to: 'home#chat'
  root 'home#index'
  
  
  
resources :conversations, only: [:index, :show, :destroy] do
  member do
    post :reply
  end
end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  @hello = 'Fam R.app!'

  def about; end

  def fusion; end

  def chat; end

  def blog; end

  def frapp_talk; end

  def maps; end

  def profile; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissable"></div>
        <button class= "close" data-dismiss="alert">
           
        </button>
        <%= content_tag(:div, msg) %>
     </div>
<% end %>

app/views/home/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
<div>
  <ul class="navbar-nav text-uppercase ml-auto">
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/users/edit">Edit account</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/users/sign_out">Sign out</a>
    </li>
  </ul>
</div>
  <!-- <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li> -->
<% else %>
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav text-uppercase ml-auto">
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/users/sign_in">Sign in</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/users/sign_up">Sign up</a>
    </li>
  </ul>
</div>
  <!-- <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li> -->
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/home/_navbar.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Agency - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="css/agency.min.css" rel="stylesheet">

  </head>
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
    <div class="container">
      <%= link_to 'Frapp', root_path, class: 'navbar-brand' %>
    </div>
    <%= render 'home/navigation_links' %>
    <%= render 'home/nav_links_for_auth' %>

  </div>
</nav>

app/views/home/_navigation_links.html.erb
<%# add navigation links to this file %>
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav text-uppercase ml-auto">
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/home/about">About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/events/upcoming">Events</a>
    </li>
    <li class="nav-item">
      <a class="nav-link js-scroll-trigger" href="/maps/google_maps">Google Maps</a>
    </li>
  </ul>
</div>

app/views/home/_oldnavbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%# image_tag("logos/logo.png", width: '150px') %> Frapp</a>
    </div>




    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">


      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Frapp", home_about_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit Profile",  edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Frapp Events</a></li>
            <li><a href="#">Frapp Culture</a></li>
            <li><a href="#">Frapp Pay</a></li>
            <li role="separator" class="divider"></li>
            <li><<%= link_to "Google Maps", maps_google_maps_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>Family Reunion App - "Frapp"</h1>



<div class="jumbotron" center>
  <h1>Team - B</h1>
<p> Glynis Monroe and Terrence Robinson </p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">About Us</a></p>
  

</div>

app/views/home/blog.html.erb
<h1>FrappBlogg</h1>


<div class="panel panel-default">
  <div class="panel-body">
   Posting the best blogs for the family past and current events.
  </div>
</div>

<body>
  <!--<nav class="navbar navbar-inverse">-->
    <!--<div class="container">-->
      <div class="navbar-header">
        <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %>
        <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %>
      
<div>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Your Blogg!', conversations_path %></li>
          <!--<li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>-->
        <% else %>
          <!--<li><%= link_to 'Log In', new_user_session_path, class: "btn btn-info"  %></li>-->
        <% end %>
 </div>
</div>

      </ul>
  </nav>
</body>

app/views/home/chat.html.erb
<h1>FrappChat</h1>


<div class="panel panel-default">
  <div class="panel-body">
   Connecting families through a messaging app..
  </div>
</div>

<body>
  <!--<nav class="navbar navbar-inverse">-->
    <!--<div class="container">-->
      <div class="navbar-header">
        <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %>
        <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %>
      
<div>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Your Convos!', conversations_path %></li>
          <!--<li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>-->
        <% else %>
          <!--<li><%= link_to 'Log In', new_user_session_path, class: "btn btn-info"  %></li>-->
        <% end %>
 </div>
</div>
      </ul>
  </nav>
</body>

app/views/home/content.html.erb
<div class="panel panel-default">
  <div class="panel-body">
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="..." alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    ...
  </div>
</div>
<div>
 <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %>
 <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %></div>
 </div>
 
 <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Frapp", home_about_path %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit Profile",  edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
       
</div>
 </div>

app/views/home/frapp_talk.html.erb
<h1>FrappTalk!</h1>
<div class="panel panel-default">
  <div class="panel-body">
   <!--Connecting families through a messaging app..-->
  </div>
</div>

<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %></br>
        <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %></br>
        <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %></br>
        </div>
      </div>
      
      <p id="notice"><%= notice %></p>

<p>
  <%= image_tag @post.image.url(:thumb) %></br>
  <strong>Body:</strong>
  <%= @post.body %>
</p>


<div>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', posts_path %>
    <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %>
</div>
       <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Your Conversations', conversations_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path, class: "btn btn-success"  %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</body>

<div>
    <%= link_to conversation.subject, conversation.(@conversation) %> 
    <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %>
    <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %></div>
    </div>
 <% end %>
</div>

<% page_header "Your Conversations" %>

<ul class="list-group">
  <%= render partial: 'conversations/conversation', collection: @conversations %>
</ul>



<% page_header "Your Conversations" %>

<p><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></p>


<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
    <ul class="list-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

<div class="col-sm-9">
  <% if @box == 'trash' %>
    <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                   data: {confirm: 'Are you sure?'} %></p>
  <% end %>
  <ul class="list-group">
    <%= render partial: 'conversations/conversation', collection: @conversations %>
  </ul>

  <%= will_paginate %>
  </div>
 </div>
</div>

app/views/home/fusion.html.erb
<h1> FrappFusion </h1> 


    <div class="panel panel-default">
      <div class="panel-body">
       A fusion of fun...detailing all the cultural events for family activities.
      </div>
    
    <div  class= "panel-primary-heading-bg">
        </div>
    </div>
    
    <body>
      <!--<nav class="navbar navbar-inverse">-->
        <!--<div class="container">-->
          <div class="navbar-header">
            <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %>
            <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %>
          </div>
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Your Life', conversations_path %></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <!--<li><%= link_to 'Log In', new_user_session_path, class: "btn btn-primary"  %></li>-->
            <% end %>
          </ul>
        </div>
    </body>
  
  

app/views/home/index.html.erb
<!-- Navigation -->
<div class="fixednav">
    <span></span>
</div>
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand">
            <a href="#top"  onclick = $("#menu-close").click(); >Start Bootstrap</a>
        </li>
        <li>
            <a href="#top" onclick = $("#menu-close").click(); >Home</a>
        </li>
        <li>
            <a href="#about" onclick = $("#menu-close").click(); >About</a>
        </li>
        <li>
            <a href="#services" onclick = $("#menu-close").click(); >Services</a>
        </li>
        <li>
            <a href="#portfolio" onclick = $("#menu-close").click(); >Portfolio</a>
        </li>
        <li>
            <a href="#contact" onclick = $("#menu-close").click(); >Contact</a>
        </li>
    </ul>
</nav>

<!-- Header -->
<header id="top" class="header">
    <div class="text-vertical-center">
        <h1>Frapp</h1>
        <h3>A Family Reunion App</h3>
        <br>
        <a href="#about" class="btn btn-dark btn-lg">Find Out More</a>
    </div>
</header>

<!-- Services -->
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Frapp Forum</h2>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading" href= '/pages/fusion'>Frapp Fusion</h4>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading" href= '/pages/chat'>Frapp Chat</h4>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="service-heading">Frapp Blog</h4>
      </div>
    </div>
  </div>
</section>

<!-- Map -->
<section id="contact" class="map">
    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d110082.41325962704!2d-84.36057602102514!3d30.43396400284983!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x88ecf56ccebb1285%3A0x9e03781dcce8ec40!2sdomi+station!3m2!1d30.433982699999998!2d-84.2905358!5e0!3m2!1sen!2sus!4v1524732682280"></iframe>
    <br />
    <small>
        <a href="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d110082.41325962704!2d-84.36057602102514!3d30.43396400284983!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x88ecf56ccebb1285%3A0x9e03781dcce8ec40!2sdomi+station!3m2!1d30.433982699999998!2d-84.2905358!5e0!3m2!1sen!2sus!4v1524732682280"></a>
    </small>
    </iframe>
</section></br></br></br></br></br></br></br></br></br>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h4><strong>Frapp</strong>
                </h4>
                <p>914 Railroad Ave<br>Tallahassee, FL 32310</p>
                <ul class="list-unstyled">
                    <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:name@example.com">name@example.com</a>
                    </li>
                </ul>
                <br>
                <ul class="list-inline">
                    <li>
                        <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                    </li>
                </ul>
                <hr class="small">
                <p class="text-muted">Copyright &copy; 2018</p>
            </div>
        </div>
    </div>
</footer>

<!-- Custom Theme JavaScript -->
<script>
// Closes the sidebar menu
$("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Opens the sidebar menu
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
});

// Scrolls to the selected menu item on the page
$(function() {
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html,body').animate({
                    scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
});
</script>

<div class="jumbotron">
  <div class="container">
    <h1 class="lead">"Celebrating families all over the world... by connecting through history, heritage and lineage."</h1>
  </div>
</div>


<h1> Frapp Forum </h1>







  <p>"Celebrating families all over the world... by connecting through history, heritage and lineage."</p>


  <%= @hello %>

  <div class="form-group">
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <div class="btn-group" role="group">
        <!--<button type="button" class="btn btn-primary">FrappFusion</button>-->
        <%= link_to 'FrappFusion', fusion_path, class: "btn btn-primary"  %>
      </div>
      <div class="btn-group" role="group">
        <!--<button type="button" class="btn btn-success">FrappChat</button>-->
        <%= link_to 'FrappChat', chat_path, class: "btn btn-success"  %>
      </div>
      <div class="btn-group" role="group">
        <!--<button type="button" class="btn btn-info">FrappBlog</button>-->
        <%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %>
      </div>
    </div>
  </div>

app/views/home/profile.html.erb
<hr class="Profile">
<div class="container target">
    <div class="row">
        <div class="col-sm-10">
             <h1 class="">Starfox221</h1>

<button type="button" class="btn btn-info">Send me a message</button>
<br>
        </div>
      <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.rlsandbox.com/img/profile.jpg"></a>

        </div>
    </div>
  <br>
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Joined</strong></span> 2.13.2014</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last seen</strong></span> Yesterday</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Real name</strong></span> Joseph
                        Doe</li>
              <li class="list-group-item text-right"><span class="pull-left"><strong class="">Role: </strong></span> Pet Sitter

                      </li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-heading">Social Media</div>
                <div class="panel-body">	<i class="fa fa-facebook fa-2x"></i>  <i class="fa fa-github fa-2x"></i>
                    <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i>  <i class="fa fa-google-plus fa-2x"></i>

                </div>
            </div>
        </div>
        <!--/col-3-->
        <div class="col-sm-9" contenteditable="false" style="">
            <div class="panel panel-default">
                <div class="panel-heading">Bio</div>
                <div class="panel-body"> A long description about me.

                </div>
            </div>
            <div class="panel panel-default target">
                <div class="panel-heading" contenteditable="false">Photo uploads</div>
                <div class="panel-body">
                  <div class="row">
				<div class="col-md-4">
					<div class="thumbnail">
						<img alt="300x200" src="http://lorempixel.com/600/200/people">
						<div class="caption">
							<h3>
								last reunion
							</h3>
							<p>
								crowd.
							</p>
							<p>

							</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="thumbnail">
						<img alt="300x200" src="http://lorempixel.com/600/200/city">
						<div class="caption">
							<h3>
                last reunion
							</h3>
							<p>
								view.
							</p>
							<p>

							</p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="thumbnail">
						<img alt="300x200" src="http://lorempixel.com/600/200/sports">
						<div class="caption">
							<h3>
                last reunion

							</h3>
							<p>
								fun
							</p>
							<p>

							</p>
						</div>
                </div>

            </div>

            </div>

        </div>

    </div>
           <div class="panel panel-default">
                <div class="panel-heading">Bio</div>
                <div class="panel-body"> A long description about me.

                </div>
</div></div>


            <div id="push"></div>
        </div>

                <div class="span3">
                    <span class="pull-right">©Copyright 2013-2014 <a href="/" title="The Bootstrap Playground">Bootply</a> | <a href="/about#privacy">Privacy</a></span>
                </div>
            </div>
        </footer>

        <script src="/plugins/bootstrap-select.min.js"></script>
        <script src="/codemirror/jquery.codemirror.js"></script>
        <script src="/beautifier.js"></script>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-40413119-1', 'bootply.com');
          ga('send', 'pageview');
        </script>
        <script>
        jQuery.fn.shake = function(intShakes, intDistance, intDuration, foreColor) {
            this.each(function() {
                if (foreColor && foreColor!="null") {
                    $(this).css("color",foreColor);
                }
                $(this).css("position","relative");
                for (var x=1; x<=intShakes; x++) {
                $(this).animate({left:(intDistance*-1)}, (((intDuration/intShakes)/4)))
                .animate({left:intDistance}, ((intDuration/intShakes)/2))
                .animate({left:0}, (((intDuration/intShakes)/4)));
                $(this).css("color","");
            }
          });
        return this;
        };
        </script>
        