config/routes.rb
Rails.application.routes.draw do
  get 'events/upcoming'

  get 'events/past'

  get 'maps/google_maps'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts
  resources :messages, only: [:new, :create]
  resources :messages
  devise_for :users
  get 'home/about'
  get 'fusion', to: 'home#fusion'
  get 'chat', to: 'home#chat'
  get 'blog', to: 'home#blog'
  get 'frapp_talk', to: 'home#blog'
  get 'maps', to: 'home/maps#maps'
  get 'content', to: 'home#chat'
  root 'home#index'
  
  
  
resources :conversations, only: [:index, :show, :destroy] do
  member do
    post :reply
  end
end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
     has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  respond_to :html
  
  def index
    @posts = Post.all
    @post_img = @posts
  end

 
  def show
    respond_with(@post)
  end


  def new
    @post = current_user.posts.build
  end

 
  def
  
   edit
   
  end

 
  def create
    @post = current_user.posts.build(post_params)
   if @post.save
    redirect_to @post, notice: 'Post was sucessfully created.'
   else
    render action: 'new'
   end
  end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
      end
    end
  
  def update
     
    if @post.update(post_params)
        redirect_to @post, notice: 'Post was sucessfully updated'.
    else
        render action: 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_url
  end
  
private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.required(:post).permit(:body, :image, :name)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this post." if @post.nil?
    end

end

 

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |post| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_field :body, class: "form-control" %>
</div>
  
<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
</div>
  
<div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
</div>
<% end %>

app/views/posts/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading"<h1>Editing Post</h1></div>
    <div class="panel-body"></br>

    <%= render 'form' %>
</div>
     <div class="panel-footer"><%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
    </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

  
      <!--<th>image</th>-->
      <!--<th>Body</th>-->
      <!--<th colspan="3"></th>-->
  

  
    <% @posts.each do |post| %>
        <%= link_to image_tag(post.image.url(:thumb)), post %></br>
        <%= post.body %></br>
        <!--</br><%= link_to 'Show', post %></br>-->
        
        <% if user_signed_in? %>
        <%= link_to 'Edit', edit_post_path(post) %></br>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></br>
        <%= link_to 'New Post', new_post_path %>
      
    <% end %>
 <% end %> 
  

app/views/posts/new.html.erb
    <div class="panel panel-default">
        <div class="panel-heading"<h1>New Post</h1></div>
        <div class="panel-body">
            
        <%= render 'form' %>
    </div>
        <div class="panel-footer"><%= link_to 'Back', posts_path %></div>
    </div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @post.image.url(:thumb) %><br/>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<% @post.user.name %><br/>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'FrappBlogg', blog_path, class: "btn btn-info"  %>

<% if @post.user == current_user %>
  <%= link_to Edit, edit_post_path(@post) %>
<% end %>
<%= link_to 'Back', posts_path %>